---
name: Build Example
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 7 2 * *

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v5
      - name: Build Caddy example
        run: |
          cd examples/flake
          nix build --override-input caddy ../.. .
          ./result/bin/caddy list-modules | grep -qFx dns.providers.powerdns
